#!/bin/sh
RED="\033[1;31m"
GREEN="\033[1;32m"
NC="\033[0m"
linter_exit_code=1
npm run lint
linter_exit_code=$?
if [ $linter_exit_code -ne 0 ]
then
  echo "${RED} ❌ Linter errors have occurred${NC}"
  exit 1
else
  echo "${GREEN} ✔ Eslint did not find any errors${NC}"
  exit 0
fi